### ISSUE TITLE
Order Help

### ISSUE THREAD

**Issue by v1b3c0d3r96** [abelectronicsuk/ABElectronics_C_Libraries#2]
Hello ABElectronics,

Last month, we ordered this product from you(https://www.abelectronics.co.uk/products/3/Raspberry-Pi-Model-A-and-B/44/Servo-Pi) and until now we dont know if it was sent or what is the status of the order. Can you help us? Please let us know if it was already sent from your place? So that atleast we know if we are waiting for something or not. Because there is no way to track the order right? Atleast let us know if you guys have send the product. Thank you so much!!! We are from philippines btw.

**Comment by abelectronicsuk** [comment]
Hello Reynard

I replied to your email you sent earlier today regarding the order. 

I am sorry that your order has not arrived. As it has been over 3 weeks since the order was sent it must have been lost in the postal system. As we have not been able to deliver your order, I have refunded your payment back to your debit/credit card.

Best regards

Brian Dorey

Tel: 01929 421070 |  http://www.abelectronics.co.uk/ http://www.abelectronics.co.uk

 https://www.facebook.com/abelectronicsswanage    https://twitter.com/abelectronicsuk    https://plus.google.com/u/0/101222105768798333113/posts    https://www.youtube.com/channel/UCGF3H0XkeN5sEVoaat5DqqQ 

AB Electronics UK, 8 Richmond Road, Swanage, Dorset, BH19 2PZ, United Kingdom

AB Electronics UK is a trading name of Apexweb Ltd which is a limited company registered in England and Wales.

Company Registration No. 08969553

Registered Offices: Bridge House, Court Road, Swanage, Dorset BH19 1DX,  United Kingdom

VAT Number: GB 178 2413 96

**Comment by v1b3c0d3r96** [comment]
Hello Brian!

We really need that order. Your libraries are the only libraries we can easily use for our project. Our project's due is in less than a month. Is there a way you can help us pay and get the item? :(

**Comment by abelectronicsuk** [comment]
Hello Reynard

You can use our libraries with the adafruit version of the servo board which you can order direct from amazon https://www.amazon.com/Adafruit-16-Channel-PWM-Servo-Raspberry/dp/B00SI1SPHS  I think that amazon should have a fully tracked delivery option for the board.

Best regards

Brian 

Tel: 01929 421070 |  http://www.abelectronics.co.uk/ http://www.abelectronics.co.uk

 https://www.facebook.com/abelectronicsswanage    https://twitter.com/abelectronicsuk    https://plus.google.com/u/0/101222105768798333113/posts    https://www.youtube.com/channel/UCGF3H0XkeN5sEVoaat5DqqQ 

AB Electronics UK, 8 Richmond Road, Swanage, Dorset, BH19 2PZ, United Kingdom

AB Electronics UK is a trading name of Apexweb Ltd which is a limited company registered in England and Wales.

Company Registration No. 08969553

Registered Offices: Bridge House, Court Road, Swanage, Dorset BH19 1DX,  United Kingdom

VAT Number: GB 178 2413 96

**Comment by v1b3c0d3r96** [comment]
Thanks Brian.

**Comment by v1b3c0d3r96** [comment]
Hello Brian, 

My friend harpreet sangar checked his account and he said the balance was not refunded. Can you double check the transaction? Thanks.
